name    'huit/openstack_gluster_swift'
version '0.1.0'
source 'UNKNOWN'
author 'huit'
license 'Apache License, Version 2.0'
summary 'Configure gluster_swift for HUIT OpenStack PoC'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/lvm', '>= 0.1.2'
dependency 'puppetlabs/mount_providers', '>= 0.0.2'
dependency 'huit/openstack_repos'
dependency 'thias/glusterfs', '>= 0.0.3'
dependency 'thias/memcached', '>= 0.1.0'
